INSERT INTO recipes_db.categories (category, createdAt, updatedAt)
VALUES 
("Breakfast", DATE(NOW()), DATE(NOW())),
("Lunch", DATE(NOW()), DATE(NOW())),
("Dinner", DATE(NOW()), DATE(NOW())),
("Dessert", DATE(NOW()), DATE(NOW())),
("Entree", DATE(NOW()), DATE(NOW())),
("Side Dish", DATE(NOW()), DATE(NOW())),
("Vegetable Dish", DATE(NOW()), DATE(NOW())),
("Snack", DATE(NOW()), DATE(NOW())),
("Easy Recipes", DATE(NOW()), DATE(NOW())),
("Fancy Fixin's", DATE(NOW()), DATE(NOW())),
("Casual Dining", DATE(NOW()), DATE(NOW())),
("Comfort Food", DATE(NOW()), DATE(NOW())),
("Grillin' Grub", DATE(NOW()), DATE(NOW())),
("Non-Chick Food", DATE(NOW()), DATE(NOW())),
("Cold Weather Cookin'", DATE(NOW()), DATE(NOW())),
("Slow Cooker", DATE(NOW()), DATE(NOW())),
("Fried Foods", DATE(NOW()), DATE(NOW())),
("Italian", DATE(NOW()), DATE(NOW())),
("Mexican", DATE(NOW()), DATE(NOW())),
("Pasta", DATE(NOW()), DATE(NOW())),
("Chili", DATE(NOW()), DATE(NOW())),
("Soup", DATE(NOW()), DATE(NOW())),
("Sandwich", DATE(NOW()), DATE(NOW())),
("Pizza", DATE(NOW()), DATE(NOW())),
("Cookies", DATE(NOW()), DATE(NOW())),
("Syrup", DATE(NOW()), DATE(NOW())),
("BBQ Sauce", DATE(NOW()), DATE(NOW())),
("Chicken", DATE(NOW()), DATE(NOW()))
;