INSERT INTO recipes_db.recipes (title, description, prepTime, cookTime, servings, directions, createdBy, createdAt, updatedAt)
VALUES 
("Reese's Pieces Soft Peanut Butter Cookies", "The cookies are soft, moist, with tender centers, a bit of chewiness  to the edges and loaded with Reese's Pieces  and chocolate chips. Packed with peanut butter flavor.", "10 minutes", "8 minutes", "About 26-28 cookies", "In a stand mixer with paddle attachment, cream together first 5 ingredients on medium  high speed until light and fluffy. About 5 minutes. Scrape down sides and add the flour and baking soda. Mix on low speed until just incorporated. About 1 minute. Add Reese's pieces, chocolate chips ,and blend until just incorporated. Using a 2 inch cookie scoop, form mounds. Place on large plate and flatten mounds with palm of your hand. Cover with plastic wrap and refrigerate for at least 2 hours. Preheat oven to 350F. Spray cookie sheet with cooking spray. Place cookies on sheet at least 2 inches apart. Cook in oven for 8 to 9 minutes", "serverBoss", DATE(NOW()), DATE(NOW())), 
("Luscious Blueberry Syrup", "Yummy fruit syrup filled with ripe blueberries. Top your favorite pancakes with it", "5 minutes", "10 minutes", "Makes 2  ½ cups", "In a saucepan over medium heat, combine sugar and cornstarch. Stir in water gradually. Add berries; bring to a boil. Boil, stirring constantly, for one minute, or until mixture thickens. Serve warm, or pour into covered jar and keep in fridge for several days", "serverBoss", DATE(NOW()), DATE(NOW())), 
("Garbage Pasta", "This is not your girlfriend's pasta. Let's talk about lots of pasta, meat, and cheese!!", "The time it takes you to open and dump packages into a pot!", "About 20 minutes to heat garbage sauce, but only 7.5 minutes for al-dente pasta!", "Depends on how much you eat yourself", "Brown the rolls of sausage and ground beef. Empty all ingredients except pasta and cheese into a large sauce pan and simmer for 10 minutes. Heat water to a boil, then add pasta for 7.5 minutes and drain. Combine pasta and sauce to your desired ratio and top with generous cheese! After all, the girlfriend is not here tonight!", "lone-girl", DATE(NOW()), DATE(NOW())),
("Potato Slop", "It's practically all butter.", "5 minutes if you know how to peel potatoes like a pro.", "About 30 minutes.", "1? 2? How hungry are you? How much space do you have left in your arteries?", "Peel potatoes. Cut potatoes into 1 inch chunks. Add potatoes to pot of cold water and bring to a boil and then reduce heat and let simmer for 12 minutes. Add salt til it tastes like the ocean water you inadvertently drank as a kid. In a saucepan, bring cream and milk to a simmer. Drain potatoes and rinse. Return them to the same pot and let the mashing commence. If  your arm or hand is cramping, you are doing it right. Add all that butter and mix it in. Add milk and cream slowly! Add salt and pepper to taste.", "kamakazi-Ben", DATE(NOW()), DATE(NOW())),
("Brussels n' Bacon", "Brussels sprouts anyone would eat!", "10 minutes", "Roughly 15 minutes", "5 American sized servings", "Cook that fatty bacon in a large skillet over medium-high heat until it's crispy. Remove bacon to drain, then rip it apart into little chunks like the animal that you are. In that same pan with all of that glorious bacon grease, melt butter over high heat. Add chopped onions and halved Brussels Sprouts and cook. It should take about 10 minutes for those suckers to be golden brown and tasty. Add salt and pepper to taste. Throw all of those bacon pieces back in, stir, and serve it up!", "kamakazi-Ben", DATE(NOW()), DATE(NOW())),
("Crock Pot Chili", "This hearty chili has a mild flavor, perfect for families with kids. It's easy to customize and add your favorite toppings.", "", "", "12 or more servings", "Soak Pinto beans overnight in water, drain and rinse the next morning. Next add diced onions and tomatoes. Add chili meat and seasoning packet along with onion powder and garlic powder, stir to mix. Then pour in beef broth. Two cups is plenty – you won’t completely cover your beans and meat, but during cooking the meat will release quite a bit of juice and fat, adding to the liquid content. We want to make chili, not soup. Cook on high for two hours in the Crock Pot. Add ketchup and Worcestershire sauce, stir to mix well. Reduce heat to low and continue to cook for 6-8 hours, stirring every couple of hours. Taste an hour or so before serving time and add salt and pepper if needed.", "lone-girl", DATE(NOW()), DATE(NOW())),
("Monster Burger", "It's delicious to eat but be careful not to dislocate your jaw!", "20 minutes", "10 minutes", "2", "Split beef into two portions and turn them into big ole patties. Make a depression in the center of the patty. Go ahead and start heating up the grill! Fry an egg in a pan to your desired consitency. I prefer over-medium. Cook 4 strips of bacon in the same pan to reduce dishes! Slice up an avocado into manageable pieces that will fit niceley on your burger. Toss those burgers on the grill, add salt and pepper to both sides. Should need roughly 6 minutes per side. Towards the end of the grilling process, butter the buns and place them on the grill for a nice crunchy bun. Remove burgers and buns from the grill. Assemble the burger and enjoy!", "kamakazi-Ben", DATE(NOW()), DATE(NOW())),
("Slow Cooker Potato Soup", "Warm and comfy soup for the soul", "15 minutes", "Low for 6 hours", "one bowl worth of soup", "Peel potatoes. Cut into small cubes and put into slow cooker.Chop onions and mince garlic. Add to the slow cooker. Sprinkle salt and pepper. Add chicken broth. Cover and cook for 6hours on low. Half hour before done, take 1’3 of the potatoes from the pot into a blender. Blend with heavy cream and pour back into the pot. Mix well and cook for half hour. Top with bacon and cheese", "serverBoss", DATE(NOW()), DATE(NOW())),
("Trap Chicken", "Crispy chicken", "20 minutes", "25-30 minutes", "2-3", "Rinse and season chicken, add mustard then season once more. Refrigerate for 10 minutes. Once the chicken has cooled, drop chicken into breader of your choice then deep fry it for about 15 minutes.", "K-Man", DATE(NOW()), DATE(NOW())),
("Chicken Bacon BBQ Pizza", "A dish for all the BBQ sauce lovers out there.", "45 minutes", "One hour", "4-5 servings", "Shred chicken and bacon before, spread your bbq sauce over your pizza crust. Dump bacon, chicken and cheese on crust and then place in oven for 40 minutes(oven should pre-heat to 400 F).", "K-Man", DATE(NOW()), DATE(NOW())),
("Grilled PB&J Sandwich", "A southern twist to an original.", "5 minutes", "None", "One servings", "Spread pb&j over bread, then grill.", "K-Man", DATE(NOW()), DATE(NOW()))
;